on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-npm-develop-${{ hashFiles('**/package-lock.json') }}
          path: layers/npm/nodejs/node_modules
      - run: cd layers/npm/nodejs && npm install
      - run: cd ../../../
      - name: Cache SAM build
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-sam-develop
          path: .aws-sam/
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env develop
